### ISSUE TITLE
Fix failing tests with exit code -1

### ISSUE THREAD

**Issue by andreilg** [MarcelGarus/glados#17] opened 2022-08-24 13:30 UTC
OS: Windows 11
IDE: IntelliJ Idea
Dart SDK: `'>=2.17.6 <3.0.0'`
Dependencies:
```yaml
#dependencies:
dev_dependencies:
  glados: ^1.1.3
  lints: ^2.0.0
  test: ^1.16.0
```

I've been practicing property-based testing with this library and I've run into a few instances of tests taking a very long time to run and eventually failing with `exit code -1`.

Here is an implementation of division where I purposefully return multiplication to test division's properties:
```dart
double div(double num1, double num2) => num1 * num2;
```
and my only test is:
```dart
Glados<double>().test('div', (num1) => expect(div(num1, num1), 1));
```
I initially thought that the test was hanging but it actually took 6 minutes to run and eventually failed without telling me on what values. It works fine when I change `num1 * num2` to `num1 / num2` so I believe the issue has something to do with glados' shrinking in regards to `double`s since the following code failed quickly without issues:
```dart
double div(int num1, int num2) => (num1 * num2).toDouble();
```
```dart
Glados<int>().test('div2', (num1) => expect(div(num1, num1), 1));
```

**Comment by MarcelGarus** [comment] 2022-08-27 20:02
Indeed, this was an error in the shrinking of `double`s. In particular, it seems like the shrinking just generated a huuuuge amount of values (which, admittedly, were all smaller than the original).

I simplified the shrinking code to turn `3.2 -> 2.2` etc. (so, move numbers one closer to zero) and after that's not working, round values to some decimal places.

Your test case (which I also added as a regression test) seems to be fixed by that.

The new version is published as 1.1.4.

**Closed** 2022-08-27 20:02 UTC
